version: '3'
services:
  nfs-server:
    image: gists/nfs-server
    container_name: nfs-server
    privileged: true
    ports:
      - "2049:2049"
    # https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_DOMAIN=*" # The visitor IP range
    volumes:
      - /shared:/nfs-share
    # restart: always